#!/usr/bin/env python3
import operator
import re
import csv

d={}

with open("syslog.log") as f:
  lines=f.readlines()
  lines=[line.strip() for line in lines]
  for l in lines:
#    print(l)
    r = re.search(r"ERROR",l)
#    print(l) if r else ""
    if r:
      es = l.split()[6:]
      es.pop()
      e=" ".join(es)
#      print(e)
      d[e]=d.get(e,0)+1
  d = sorted(d.items(), key = operator.itemgetter(1), reverse=True)

with open("error_message.csv","w") as f :
  w=csv.writer(f)
  w.writerow(["Error","Count"])
  w.writerows(d)
